### ISSUE TITLE
Onboarding Channel + Onboarding Checklist

### ISSUE THREAD

**Issue by Fryuni** [astrolicious/dotdev#102]

**Comment by florian-lefebvre** [comment]
We need to account for several types of "projects" (if that's even the right term). Eg: code projects, content creators.

For code projects, I think the onboarding should ask for the following:
- git repo url
- website url (optional)
- docs completeness + url
- tests completeness + url
- I think we talked about more criteria but can't remember
- do they have specific channels needs (default being 1 public, 1 private and 1 internal for convo with staff (us))
- do they need an astrolicious subdomain
- what is the state of their project: do they need a guidance on specific topics, how can we help them

I think a channel using needle (like for the astro jobs channel) would be ideal so that people can get a template

**Comment by alexanderniebuhr** [comment]
GitHub Issue Template https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
